version: '3.3'
services:
  db:
    container_name: db
    image: mariadb:10.5.4
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wp-network

  wordpress:
    depends_on:
      - db
    container_name: wordpress
    image: wordpress:php7.2-fpm
    volumes:
      - wp_data:/var/www/html
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    networks:
      - wp-network

  webserver:
    depends_on:
      - wordpress
    container_name: webserver
    image: nginx:stable
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wp_data:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - wp-network

volumes:
  db_data:
  wp_data:
    driver_opts:
      type: none
      device: ${WORDPRESS_DATA}
      o: bind

networks:
  wp-network:
    driver: bridge