version: '3.3'
services:
  wordpress:
    container_name: wordpress
    image: wordpress:php7.4-fpm
    volumes:
      - wp_data:/var/www/html
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    networks:
      - wp-network

  webserver:
    depends_on:
      - wordpress
    container_name: webserver
    image: nginx:stable
    restart: unless-stopped
    ports:
      - "${WEBSERVER_PORT}:80"
    volumes:
      - wp_data:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - wp-network

volumes:
  wp_data:
    driver_opts:
      type: none
      device: ${WORDPRESS_DATA}
      o: bind

networks:
  wp-network:
    driver: bridge